### ISSUE TITLE
Question: On TLS info.

### ISSUE THREAD

**Issue by ealashwali** [april/certainly-something#25]
Thanks for this nice tool. Just a simple question plz: When you extarct TLS info (e.g. certificates, or anything else) which headers you are considering exactly? 

For example, when I tested FF webRequest.getSecurityInfo on the following URL: `https://yahoo.com`. There are several automatic redirect occurs in my browser untill the URL bar lands on: `https://uk.yahoo.com/?p=us&guccounter=1`. For each URL during the automatic redirect, I receive headers. In your tool, which headers you are considering? the last one? the first one? Can you clarify what is the correct way to deal with multiple headers due to automatic redirection?

**Comment by rugk** [comment]
No [HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) are ever considered. TLS info is extracted from the certificate that is sent. And this is send _before_ any things from HTTP, including headers, are sent.

**Comment by ealashwali** [comment]
Thanks. Even the first part (under the title "handshake")? Is this in the certificates? 
But even the certificates is received per header s I am receiving the chains repeatedly. I just want the certificate of the embarked URL. For example, to extract the certs. chain, I get them from securityInfo.certificates, but the `webRequest.SecurityInfo`, which according to the [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/getSecurityInfo) (note the onHeadersReceived): "You can only call this function from inside the webRequest.onHeadersReceived listener. ".

**Comment by ealashwali** [comment]
So if you do not use 
`webRequest.onHeadersReceived` what do you use?

**Comment by rugk** [comment]
> Even the first part (under the title "handshake")? Is this in the certificates?

No, that is part of the [handshake](https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_handshake). https://tls.ulfheim.net/ is a nice explanation/illustration of the whole process.

> So if you do not use `webRequest.onHeadersReceived` what do you use?

[That's easy to find out.](https://github.com/april/certainly-something/search?q=webRequest&unscoped_q=webRequest)

> according to the [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/getSecurityInfo) (note the onHeadersReceived): "You can only call this function from inside the webRequest.onHeadersReceived listener. ".

Yes, but this does not mean it's received inside of the headers. HTTP is a layer on top of TLS, so it "comes later". First the TLS connection is built, then the HTTP on the encrypted channel TLS provides.
Actually, I guess, it is just in this callback [because this is the first callback you have after the connection is established](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest).

----

Generally, what are you trying to acomplish?
It seems you are writing your own WebExtension. While I guess it is not bad to look at other add-ons, asking here may be the wrong forum for that. Stackexchange or https://discourse.mozilla.org/ may help a little more.

That said, I guess it is a good idea to look at the _code_ of this add-on here.

---

> But as I said, I receive many headers per URL, even when I specify the URL type to be `main_frame` due to redirections.

Yes, IIRC `main_frame` is just that it does not trigger for iframes or so, redirects are still in the `main_frame`.

About your redirect problem: Yes, if you do not stop the redirect/request, the redirects likely occur and trigger your callback each time, so you get many add-ons. 
So either you somehow ignore the other headers, or you e.g. [modify the request](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest#Modifying_requests) so it does not redirect. (However, users will see this, obviously.)

Generally, as said, elaborate your problem a little on a platform that is suited for asking programming questions.
